Order contains multiple qualities of a product
hpi-epic/pricewars-merchant pull request #15
Opened 2018-08-27 15:20 UTC by CarstenWalther

This pull request updates the merchant to the new producer API changes. Mainly, an order from the producer contains a list of products in different qualities.

The example merchants store ordered products in a list. If a merchant creates a new offer, he takes products from that list. If the list is empty, the merchant orders new products to refill the list.

I also remove many producer API calls because merchants should not be allowed to reconfigure the producer.

2018-09-04 12:08 UTC, Bouncner commented on pricewars_merchant.py
> -        self.inventory_level += order.product.amount
We should try to get rid of `amount` when we actually talk about the `number of` or `counts`.

2018-09-04 12:12 UTC, Bouncner requested changes

2018-09-04 12:12 UTC, Bouncner commented on pricewars_merchant.py
>          order = self.producer.order(self.settings['restock limit'])
We have setting keys like `'restock limit'` and `'primeShipping'`. We should decide for either camel case or underscores (or even spaces, but we should unify all keys).

2018-09-04 12:12 UTC, Bouncner commented on api/producer.py
>          r = self.request('post', 'orders', data={'amount': amount})
We shoud get rid of `amount` and rather use `count` or `number_of...`.

2018-09-04 18:21 UTC, CarstenWalther commented
I've also used underscore naming for strategy names to make it easier to use in terminal

2018-09-05 08:44 UTC, Bouncner approved these changes

2018-09-05 08:44 UTC, Bouncner commented
Will merge in October, when the currently running semester has finished.

2018-10-02 12:02 UTC, merged